--exec sp_update_price
IF OBJECTPROPERTY(object_id('dbo.sp_update_price'), N'IsProcedure') = 1
DROP PROCEDURE [dbo].[sp_update_price]
GO
CREATE PROCEDURE dbo.sp_update_price
AS 
BEGIN 
BEGIN TRANSACTION

/* UPDATE THE PRICE TABLE ASSUMING ITS EMPTY */
INSERT INTO T_PRICE(PRO_ID, PRO_PRICE)
SELECT PRO_ID, PRO_BASE
FROM T_PRODUCT;
/* ROLLBACK ON ERROR */
IF @@error <> 0

	BEGIN
		ROLLBACK TRANSACTION
		SELECT ' Insert was unsuccessful'
		RETURN
	END

COMMIT TRANSACTION;
SELECT * FROM T_PRODUCT;
END